# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const PLAY = "PLAY"
const OPTIONS = "OPTIONS"
const EXIT = "EXIT"
const MM_BUGS = "MM_BUGS"
const MM_WEB = "MM_WEB"
const MM_BUGHATERS = "MM_BUGHATERS"
const EXTRAS = "EXTRAS"
const MODS = "MODS"
const CREDITS = "CREDITS"
const PAUSE = "PAUSE"
const S_C_AUDIO = "S_C_AUDIO"
const S_C_VIDEO = "S_C_VIDEO"
const S_C_OTHER = "S_C_OTHER"
const S_FULLSCREEN = "S_FULLSCREEN"
const S_RES = "S_RES"
const S_COLORS = "S_COLORS"
const S_COLORS_P = "S_COLORS_P"
const S_COLORS_D = "S_COLORS_D"
const S_COLORS_T = "S_COLORS_T"
const S_COLORS_GRAY = "S_COLORS_GRAY"
const S_COLORS_RETRO = "S_COLORS_RETRO"
const S_COLORS_OFF = "S_COLORS_OFF"
const S_LANG = "S_LANG"
const S_LANG_EN = "S_LANG_EN"
const S_LANG_PL = "S_LANG_PL"
const S_LANG_DE = "S_LANG_DE"
const S_SAVE = "S_SAVE"
const S_SAVE_SAE = "S_SAVE_SAE"
const S_SAVE_EXIT = "S_SAVE_EXIT"
const SAV_CHOOSE = "SAV_CHOOSE"
const SAV_CREATED = "SAV_CREATED"
const SAV_SAVEAT = "SAV_SAVEAT"
const SAV_CR_CREATE = "SAV_CR_CREATE"
const SAV_CR_SVNAME = "SAV_CR_SVNAME"
const SAV_CR_PLNAME = "SAV_CR_PLNAME"
const SAV_CR_DONE = "SAV_CR_DONE"
const RESUME = "RESUME"
const SAE = "SAE"
const PLEASED = "PLEASED"
const MAINMENU = "MAINMENU"
const CANCEL = "CANCEL"
const PHOTOMODE = "PHOTOMODE"
const USE = "USE"
const BACK = "BACK"
const AUTOSAVEMSG = "AUTOSAVEMSG"
const MODS_LOAD = "MODS_LOAD"
const MODS_DOWNLOAD = "MODS_DOWNLOAD"
const MODS_WARN = "MODS_WARN"

const KEYS = [
 "PLAY",
 "OPTIONS",
 "EXIT",
 "MM_BUGS",
 "MM_WEB",
 "MM_BUGHATERS",
 "EXTRAS",
 "MODS",
 "CREDITS",
 "PAUSE",
 "S_C_AUDIO",
 "S_C_VIDEO",
 "S_C_OTHER",
 "S_FULLSCREEN",
 "S_RES",
 "S_COLORS",
 "S_COLORS_P",
 "S_COLORS_D",
 "S_COLORS_T",
 "S_COLORS_GRAY",
 "S_COLORS_RETRO",
 "S_COLORS_OFF",
 "S_LANG",
 "S_LANG_EN",
 "S_LANG_PL",
 "S_LANG_DE",
 "S_SAVE",
 "S_SAVE_SAE",
 "S_SAVE_EXIT",
 "SAV_CHOOSE",
 "SAV_CREATED",
 "SAV_SAVEAT",
 "SAV_CR_CREATE",
 "SAV_CR_SVNAME",
 "SAV_CR_PLNAME",
 "SAV_CR_DONE",
 "RESUME",
 "SAE",
 "PLEASED",
 "MAINMENU",
 "CANCEL",
 "PHOTOMODE",
 "USE",
 "BACK",
 "AUTOSAVEMSG",
 "MODS_LOAD",
 "MODS_DOWNLOAD",
 "MODS_WARN"
]